import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Board from "./component/Board";

export default function Home() {
  const [squares, setSquares] = useState(Array(9).fill(null));
  const [clicked, setClicked] = useState<null | string>(null);
  const [activePlayer, setActivePlayer] = useState<string>("X");
  const [winner, setWinner] = useState<string>("");

  const handleSquareClick = (index) => {
    const clickedBox = squares.map((square, i) => {
      if (index === i) {
        return activePlayer;
      } else {
        return square;
      }
    });
    setSquares(clickedBox);
    setActivePlayer(activePlayer === "X" ? "O" : "X");
  };

  const calculateWinner = () => {
    const lines = [
      [0, 1, 2],
      [3, 4, 5],
      [6, 7, 8],
      [0, 3, 6],
      [1, 4, 7],
      [2, 5, 8],
      [0, 4, 8],
      [2, 4, 6],
    ];

    for (let i = 0; i < lines.length; i++) {
      const [a, b, c] = lines[i];

      if (
        squares[a] &&
        squares[a] === squares[b] &&
        squares[b] === squares[c]
      ) {
        setWinner(squares[a]);
      }
    }
  };
  useEffect(() => {
    calculateWinner();
  });

  const handleReset = () => {
    setSquares(Array(9).fill(null));
    setWinner("");
  };

  return (
    <div className='container'>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {winner ? (
        <h2>Player {winner} wins</h2>
      ) : (
        <h2>Hey player {activePlayer}, it is your turn</h2>
      )}
      <div className='board_container'>
        {Array(9)
          .fill(null)
          .map((square, index) => (
            <Board
              clicked={clicked}
              key={index}
              activePlayer={activePlayer}
              onClick={() => handleSquareClick(index)}
              value={squares[index]}
              winner={winner}
            />
          ))}
      </div>
      <button className='reset' onClick={() => handleReset()}>
        Reset Game
      </button>
    </div>
  );
}
