import { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Board from "./component/Board";

type Player = {
  activePlayer: "X" | "O";
  player_X: Boolean;
  onClick: () => void;
};

export default function Home() {
  const [squares, setSquares] = useState(Array(9).fill(null));
  const [clicked, setClicked] = useState<null | string>(null);
  const [activePlayer, setActivePlayer] = useState<string>("X");

  const handleSquareClick = (index) => {
    const clickedBox = squares.map((square, i) => {
      if (index === i) {
        return activePlayer;
      } else {
        return square;
      }
    });
    setSquares(clickedBox);
    console.log(squares);
    setActivePlayer(activePlayer === "X" ? "O" : "X");
  };

  useEffect(() => {
    const lines = [
      [0, 1, 2],
      [3, 4, 5],
      [6, 7, 8],
      [0, 3, 6],
      [1, 4, 7],
      [2, 5, 8],
      [0, 4, 8],
      [2, 4, 6],
    ];
  });

  // useEffect(() => {
  //   setActivePlayer(activePlayer);
  // }, [activePlayer, player_X]);

  return (
    <div className='container'>
      <Head>
        <title>Tic Tac Toe</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h3>Hey {activePlayer} it is your turn</h3>
      <div className='board_container'>
        {Array(9)
          .fill(null)
          .map((square, index) => (
            <Board
              setClicked={setClicked}
              clicked={clicked}
              key={index}
              activePlayer={activePlayer}
              onClick={() => handleSquareClick(index)}
              value={squares[index]}
            />
          ))}
      </div>
      <button className='reset'>Reset Game</button>
    </div>
  );
}
